---
name: GenerateAdlists

on:
    schedule:
        - cron: "0 * * * *"
        - cron: "*/5 * * * *"

jobs:
    release:
        runs-on: ubuntu-latest
        name: "Generate Adlists"
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: lts/*
            - name: Echoing the tag name
              run: |
                npm test
                git commit -m "$(date +"%Y.%m.%d_%H:%M:%S")"
                git push -u origin HEAD
                gh release create $(date +"%Y.%m.%d_%H:%M:%S") --latest=true -t $(date +"%Y.%m.%d_%H:%M:%S")
