on:
  push:
    tags:
        - '*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetching Newly Registered Domains for Previous 14 & 30 Days
        run: |
            bash scripts/generateAdblockProCombined.sh nrd14.txt https://gist.githubusercontent.com/rtsfred3/8553b13be1263ccd5c296f5eb512e6e9/raw/nrd14.abp
            bash scripts/generateAdblockProCombined.sh nrd30.txt https://gist.githubusercontent.com/rtsfred3/8553b13be1263ccd5c296f5eb512e6e9/raw/nrd30.abp
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          make_latest: true
          body: Blocklists have been updated
          files: |
            abp/adaway.adblock.txt.gz
            abp/adlist.adblock.txt.gz
            abp/advertising.adblock.txt.gz
            abp/frellwits.swedish.adblock.txt.gz
            abp/hagezi.native.adblock.txt.gz
            abp/mullvad.malware.adblock.txt.gz
            abp/mullvad.trackers.adblock.txt.gz
            abp/ph00lt0.blocklist.adblock.txt.gz
            abp/urlhaus.hostfile.adblock.txt.gz
            abp/nrd14.txt.gz
            abp/nrd30.txt.gz