on:
  push:
    tags:
        - '*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    #   - name: Create Release
    #     id: create_release
    #     uses: actions/create-release@v1
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     with:
    #       tag_name: ${{ github.ref }}
    #       release_name: ${{ github.ref }}
    #       body: |
    #         Blocklists have been updated
    #       draft: false
    #       prerelease: false
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          make_latest: true
          body: Blocklists have been updated
          files: |
            abp/adaway.adblock.txt.gz
            abp/adlist.adblock.txt.gz
            abp/advertising.adblock.txt.gz
            abp/frellwits.swedish.adblock.txt.gz
            abp/hagezi.native.adblock.txt.gz
            abp/mullvad.malware.adblock.txt.gz
            abp/mullvad.trackers.adblock.txt.gz
            abp/ph00lt0.blocklist.adblock.txt.gz
            abp/urlhaus.hostfile.adblock.txt.gz